url: ""  # 로컬에서 경로가 루트로 시작하도록
baseurl: ""
avatar: /avatar.jpeg
cover_image: /bg.jpeg

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin